routes/admin.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

Route::get('/change-password', 'AuthController@changePassword')->name('change_password');
    Route::post('/change-password', 'AuthController@postChangePassword');

Route::get('/', [DashboardController::class, 'index'])->name('index');

Route::resources([
    'posts' => PostController::class,
    'categories' => CategoryController::class,
    'subjects' => SubjectController::class
]);

routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes([
    'register' => false,
    'reset' => false
]);

Route::get('/', function () {
    return view('welcome');
})->name('index');
Route::middleware('auth')->group(function () {
    Route::get('/change-password', [AuthController::class, 'changePassword'])->name('change_password');
    Route::post('/change-password', [AuthController::class, 'postChangePassword']);

    Route::redirect('/admin', '/dashboard', 301);
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::post('medias/editor-upload', [MediaController::class, 'editorUpload']);

    Route::resources([
        'categories' => CategoryController::class,
        'medias' => MediaController::class,
        'posts' => PostController::class,
        'subjects' => SubjectController::class
    ]);

    Route::prefix('categories')->name('categories.')->group(function () {
        Route::post('data-table', [CategoryController::class, 'getTableData']);
    });

    Route::prefix('posts')->name('posts.')->group(function () {
        Route::post('data-table', [PostController::class, 'getTableData']);
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Optix\Media\HasMedia;

class Post extends Model
{
    use HasFactory;
    use HasMedia;
    use SoftDeletes;

    public static function booted()
    {
        static::creating(function ($post) {
            $post->fill([
                'author_id' => Auth::id(),
                'slug' => \make_slug($post->title)
            ]);
        });

        static::updating(function ($post) {
            $post->fill([
                'slug' => \make_slug($post->title)
            ]);
        });
    }

    protected $table = 'posts';

    protected $fillable = [
        'title', 'slug', 'description', 'content', 'source_url', 'published_at', 'author_id'
    ];

    protected $casts = [
        'published_at' => 'datetime:Y-m-d'
    ];

    /** Relationship n - 1 */
    public function author()
    {
        return $this->belongsTo('App\Models\User', 'author_id', 'id');
    }

    /** Relationship 1 - n */

    /** Relationship n - n */
    public function categories()
    {
        return $this->belongsToMany('App\Models\Category');
    }

    public function subjects()
    {
        return $this->belongsToMany('App\Models\Subject');
    }

    /** Scope */
    public function scopeOnlyPublished($query)
    {
        return $query->whereDate('published_at', '<=', now());
    }
}

app/Http/Controllers/API/PostController.php
<?php

namespace App\Http\Controllers\API;

use App\Core\Businesses\API\Contracts\PostInterface as PostBusiness;
use App\Http\Controllers\Controller;
use App\Http\Resources\Collection\PostCollection;
use App\Http\Resources\Resources\PostResource;
use Illuminate\Http\Request;

class PostController extends Controller
{
    private $postBusiness;

    public function __construct(PostBusiness $postBusiness)
    {
        $this->postBusiness = $postBusiness;
    }

    public function index(Request $request)
    {
        $options = [
            'paginate' => $request->page_size ?? 10,
        ];

        $categoryIds = $this->getCategoryIds($request->category_ids);

        $options = array_merge($request->except(['page_size', 'fields', 'category_ids']), $options);

        $postList = $this->postBusiness->index($categoryIds, $options);

        return new PostCollection($postList);
    }

    public function show($slug)
    {
        return new PostResource($this->postBusiness->show($slug));
    }

    private function getCategoryIds($categoryParam)
    {
        if (! $categoryParam) {
            return null;
        }

        if (is_array($categoryParam)) {
            return $categoryParam;
        }

        return [$categoryParam];
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Core\Businesses\Contracts\PostInterface as PostBusiness;
use App\Http\Requests\CreatePostRequest;
use App\Http\Requests\EditPostRequest;
use Illuminate\Http\Request;

class PostController extends Controller
{
    private $postBusiness;

    public function __construct(PostBusiness $postBusiness)
    {
        $this->postBusiness = $postBusiness;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = $this->postBusiness->create();

        return view('posts.update', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $data = $request->only(['title', 'category_ids', 'description', 'content', 'published_at', 'source_url', 'thumbnail']);

        $result = $this->postBusiness->store($data);

        if ($result['success']) {
            return redirect()->route('posts.index')->with(['updatePost' => 'create']);
        }

        return back()->withInput()->withErrors(['common' => $result['messages']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return response()->json([
            'post' => $this->postBusiness->show($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->postBusiness->edit($id);

        return view('posts.update', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditPostRequest $request, $id)
    {
        $data = $request->only(['title', 'category_ids', 'description', 'content', 'published_at', 'source_url', 'thumbnail']);

        $result = $this->postBusiness->update($id, $data);

        if ($result['success']) {
            return redirect()->route('posts.index')->with(['updatePost' => 'edit']);
        }

        return back()->withInput()->withErrors(['common' => $result['messages']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return response()->json(
            $this->postBusiness->destroy($id)
        );
    }

    public function getTableData(Request $request)
    {
        return $this->postBusiness->getTableData($request);
    }
}

resources/views/posts/index.blade.php
@extends('layouts.master')

@section('title', 'Posts Management')

@section('plugin_stylesheets')
<!-- DataTables -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<!-- SweetAlert2 -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
@endsection

@section('stylesheets')
@endsection

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Posts <a href="{{ route('posts.create') }}" class="btn btn-success btn-xs">Add New</a>
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active">Posts</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <!-- DataTable -->
        <div class="card">
            <div class="card-body">
                <table id="posts-datatable" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Categories</th>
                            <th>Published At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Categories</th>
                            <th>Published At</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</section>
@endsection

@section('plugin_scripts')
<!-- DataTables -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}">
</script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}">
</script>

<!-- SweetAlert2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
@endsection

@section('scripts')
@if(session('updatePost'))
<script>
    window.updatePost = "{{ session('updatePost') }}";
</script>
@endif
<script src="{{ mix('js/posts.js') }}"></script>
@endsection

resources/views/posts/update.blade.php
@extends('layouts.master')

@section('title', $pageTitle.' Post')

@section('plugin_stylesheets')
    <link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}"/>
    <link rel="stylesheet"
          href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}"/>

    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet"
          href="{{ asset('vendors/admin-lte-3.0.5/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}"/>

    <link rel="stylesheet" href="{{ asset('vendors/editor-md/css/editormd.css') }}"/>
@endsection


@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        Posts
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('posts.index') }}">Posts</a></li>
                        <li class="breadcrumb-item active">{{ $pageTitle }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- Filter -->
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">
                                {{ $pageTitle }} Post
                            </h3>
                        </div>

                        <div class="card-body">
                            <form role="form" method="POST" action="{{ $formInfo['url'] }}" id="posts-create-form"
                                  enctype="multipart/form-data">
                                @csrf
                                @method($formInfo['method'])

                                <div class="row">
                                    @error('common')
                                    <div class="alert alert-danger col-12">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="title">Title</label>
                                            <input class="form-control @error('title') is-invalid @enderror" id="title"
                                                   name="title" value="{{ $post->title }}"/>
                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="published_at">Publish Time</label>
                                            <input class="form-control @error('published_at') is-invalid @enderror"
                                                   name="published_at" id="published_at" data-toggle="datetimepicker"
                                                   data-target="#published_at" value="{{ $post->published_at }}"/>
                                            @error('published_at')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="category_ids">Categories</label>
                                            <select
                                                class="form-control select2bs4 @error('category_ids') is-invalid @enderror"
                                                id="category_ids" name="category_ids[]" multiple>
                                                @foreach ($categoryList as $category)
                                                    <option value="{{ $category->id }}"
                                                        {{ $post->categories->contains('id', $category->id) ? 'selected' : '' }}>
                                                        {{ $category->name }}</option>
                                                @endforeach
                                            </select>
                                            @error('category_ids')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="source_url">Source URL</label>
                                            <input type="text"
                                                   class="form-control @error('source_url') is-invalid @enderror"
                                                   id="source_url" name="source_url">
                                            @error('source_url')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"
                                                           class="custom-file-input @error('thumbnail') is-invalid @enderror"
                                                           id="inputGroupFile01" name="thumbnail">
                                                    <label class="custom-file-label"
                                                           for="inputGroupFile01">{{ $post->thumbnail_label }}</label>
                                                </div>
                                            </div>
                                            @error('thumbnail')
                                            <span class="invalid-feedback d-block" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="description">Description</label>
                                            <textarea name="description" id="description" rows="4"
                                                      class="form-control @error('description') is-invalid @enderror">{{ $post->description }}</textarea>
                                            @error('description')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label>Content</label>
                                            <div id="my-editor">
                                                {{--                                            <textarea name="content"--}}
                                                {{--                                                      class="form-control @error('content') is-invalid @enderror">{{ $post->content }}</textarea>--}}
                                                <my-editor :id-name="`content`"></my-editor>
                                            </div>
                                            <textarea style="display: none"
                                                      name="content">{{ $post->content }}</textarea>
                                            @error('content')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-12 text-center">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                        <a href="{{ route('posts.index') }}" type="button"
                                           class="btn btn-warning">Cancel</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section('plugin_scripts')
    <script src="{{ asset('vendors/admin-lte-3.0.5/plugins/moment/moment.min.js') }}"></script>

    <!-- Select2 -->
    <script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>

    <script
        src="{{ asset('vendors/admin-lte-3.0.5/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}">
    </script>

    <script
        src="{{ asset('vendors/admin-lte-3.0.5/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>

    <script src="{{ asset('vendors/editor-md/editormd.min.js') }}"></script>
    <script>
        var editorLibPath = "{{ asset('vendors/editor-md/lib/') }}/";
    </script>

    <script>
        {{--    hljs.initHighlightingOnLoad();--}}
        bsCustomFileInput.init();
    </script>
    <script src="{{ mix('js/editor.js') }}"></script>
@endsection


@section('scripts')
    <script src="{{ mix('js/posts.js') }}"></script>
@endsection