routes/admin.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

Route::get('/change-password', 'AuthController@changePassword')->name('change_password');
    Route::post('/change-password', 'AuthController@postChangePassword');

Route::get('/', [DashboardController::class, 'index'])->name('index');

Route::resources([
    'posts' => PostController::class,
    'categories' => CategoryController::class,
    'subjects' => SubjectController::class
]);

routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes([
    'register' => false,
    'reset' => false
]);

Route::get('/', function () {
    return view('welcome');
})->name('index');
Route::middleware('auth')->group(function () {
    Route::get('/change-password', [AuthController::class, 'changePassword'])->name('change_password');
    Route::post('/change-password', [AuthController::class, 'postChangePassword']);

    Route::redirect('/admin', '/dashboard', 301);
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::post('medias/editor-upload', [MediaController::class, 'editorUpload']);

    Route::resources([
        'categories' => CategoryController::class,
        'medias' => MediaController::class,
        'posts' => PostController::class,
        'subjects' => SubjectController::class
    ]);

    Route::prefix('categories')->name('categories.')->group(function () {
        Route::post('data-table', [CategoryController::class, 'getTableData']);
    });

    Route::prefix('posts')->name('posts.')->group(function () {
        Route::post('data-table', [PostController::class, 'getTableData']);
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    public static function booted()
    {
        static::creating(function ($category) {
            $category->fill([
                'slug' => \make_slug($category->name)
            ]);
        });

        static::updating(function ($category) {
            $category->fill([
                'slug' => \make_slug($category->name)
            ]);
        });
    }

    protected $table = 'categories';

    protected $fillable = [
        'name', 'slug', 'parent_id', 'description'
    ];

    /** Relationship n - 1 */
    public function categoryParent()
    {
        return $this->belongsTo('App\Models\Category', 'parent_id', 'id');
    }

    /** Relationship 1 - n */
    public function categoryChildren()
    {
        return $this->hasMany('App\Models\Category', 'parent_id', 'id');
    }

    /** Relationship n - n */
    public function posts()
    {
        return $this->belongsToMany('App\Models\Post');
    }

    public function subjects()
    {
        return $this->belongsToMany('App\Models\Subject');
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Core\Businesses\API\Contracts\CategoryInterface as CategoryBusiness;
use App\Http\Controllers\Controller;
use App\Http\Resources\Collection\CategoryCollection;
use App\Http\Resources\Resources\CategoryResource;

class CategoryController extends Controller
{
    private $categoryBusiness;

    public function __construct(CategoryBusiness $categoryBusiness)
    {
        $this->categoryBusiness = $categoryBusiness;
    }

    public function index()
    {
        return new CategoryCollection($this->categoryBusiness->index());
    }

    public function show($slug)
    {
        return new CategoryResource($this->categoryBusiness->show($slug));
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Core\Businesses\Contracts\CategoryInterface as CategoryBusiness;
use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\EditCategoryRequest;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    private $categoryBusiness;

    public function __construct(CategoryBusiness $categoryBusiness)
    {
        $this->categoryBusiness = $categoryBusiness;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = $this->categoryBusiness->create();

        return view('categories.update', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $data = $request->only(['name', 'parent_id', 'description']);

        $result = $this->categoryBusiness->store($data);

        if ($result['success']) {
            return redirect()->route('categories.index')->with(['updateCategory' => 'create']);
        }

        return back()->withInput()->withErrors(['common' => $result['messages']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return response()->json([
            'category' => $this->categoryBusiness->show($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->categoryBusiness->edit($id);

        return view('categories.update', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditCategoryRequest $request, $id)
    {
        $data = $request->only(['name', 'parent_id', 'description']);

        $result = $this->categoryBusiness->update($id, $data);

        if ($result['success']) {
            return redirect()->route('categories.index')->with(['updateCategory' => 'edit']);
        }

        return back()->withInput()->withErrors(['common' => $result['messages']]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return response()->json(
            $this->categoryBusiness->destroy($id)
        );
    }

    public function getTableData(Request $request)
    {
        return $this->categoryBusiness->getTableData($request);
    }
}

resources/views/categories/index.blade.php
@extends('layouts.master')

@section('title', 'Categories Management')


@section('plugin_stylesheets')
<!-- DataTables -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<!-- SweetAlert2 -->
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
@endsection

@section('stylesheets')
@endsection

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Categories <a href="{{ route('categories.create') }}" class="btn btn-success btn-xs">Add New</a>
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active">Categories</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <!-- DataTable -->
        <div class="card">
            <div class="card-body">
                <table id="categories-datatable" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Parent</th>
                            <th>Posts/Subjects Count</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Parent</th>
                            <th>Posts/Subjects Count</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <!-- End DataTable -->
    </div>
</section>
@endsection


@section('plugin_scripts')
<!-- DataTables -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}">
</script>
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}">
</script>
<!-- SweetAlert2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
@endsection


@section('scripts')
@if(session('updateCategory'))
<script>
    window.updateCategory = "{{ session('updateCategory') }}";
</script>
@endif
<script src="{{ mix('js/categories.js') }}"></script>
@endsection

resources/views/categories/update.blade.php
@extends('layouts.master')

@section('title', $pageTitle . ' Category')

@section('plugin_stylesheets')
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet"
    href="{{ asset('vendors/admin-lte-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.css') }}">
@endsection

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    Categories
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categories</a></li>
                    <li class="breadcrumb-item active">{{ $pageTitle }}</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Filter -->
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ $pageTitle }} Category
                        </h3>
                    </div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ $formInfo['url'] }}" id="categories-create-form">
                            @csrf
                            @method($formInfo['method'])
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input class="form-control @error('name') is-invalid @enderror" id="name"
                                            name="name" value="{{ $category->name }}" />
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="parent">Parent</label>
                                        <select name="parent_id" id="parent"
                                            class="form-control select2bs4 @error('parent_id') is_invalid @enderror">
                                            @foreach ($parentList as $parentCategory)
                                            <option value="{{ $parentCategory->id }}"
                                                {{ $category->parent_id == $parentCategory->id ? 'selected' : '' }}>
                                                {{ $parentCategory->name }}</option>
                                            @endforeach
                                        </select>
                                        @error('parent_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea class="form-control @error('description') is-invalid @enderror"
                                                  rows="4"
                                                  name="description"
                                                  id="description">{{ $category->description }}</textarea>
                                        @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('categories.index') }}" type="button"
                                        class="btn btn-warning">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Filter -->
            </div>
        </div>
    </div>
</section>
@endsection

@section('plugin_scripts')
<!-- Select2 -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/select2/js/select2.full.min.js') }}"></script>

<!-- Summernote -->
<script src="{{ asset('vendors/admin-lte-3.0.5/plugins/summernote/summernote-bs4.min.js') }}"></script>
@endsection


@section('scripts')
<script src="{{ mix('js/categories.js') }}"></script>
@endsection